source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/close-dev-team/close-cocoapods-specs.git'
platform :ios, '12.0'

target 'Close Channel Sample' do
  use_frameworks!

  pod 'CloseChannel', '1.5.4'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|

            config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'

            if target.name == 'SwiftSocket'
              config.build_settings['SWIFT_VERSION'] = '5.0'
            end
        end
    end
end
